### ISSUE TITLE
Traceback (most recent call last):   File "bot.py", line 35, in <module>     bot = Mee6(shard_id=int(shard), shard_count=int(shard_count), redis_url=redis_url,   File "/mnt/c/users/vramp/mee6/chat-bot/mee6.py", line 29, in __init__     self.db = Db(self.redis_url, self.mongo_url, self.loop)   File "/mnt/c/users/vramp/mee6/chat-bot/database.py", line 16, in __init__     self.redis_address = parse_redis_url(redis_url)   File "/mnt/c/users/vramp/mee6/chat-bot/utils.py", line 8, in parse_redis_url     result = re.match(pattern, redis_url).groups()   File "/usr/lib/python3.8/re.py", line 191, in match     return _compile(pattern, flags).match(string) TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by AwesomeKids652** [jtagt/mee6#18]
Traceback (most recent call last):
  File "bot.py", line 35, in <module>
    bot = Mee6(shard_id=int(shard), shard_count=int(shard_count), redis_url=redis_url,
  File "/mnt/c/users/vramp/mee6/chat-bot/mee6.py", line 29, in __init__
    self.db = Db(self.redis_url, self.mongo_url, self.loop)
  File "/mnt/c/users/vramp/mee6/chat-bot/database.py", line 16, in __init__
    self.redis_address = parse_redis_url(redis_url)
  File "/mnt/c/users/vramp/mee6/chat-bot/utils.py", line 8, in parse_redis_url
    result = re.match(pattern, redis_url).groups()
  File "/usr/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
that is my issue

**Comment by laggycomputer** [comment]
I apologize for this not being more apparent, but this project is effectively dead.
Among other things:
- Discord intents require deliberate enabling for every bot running this. Unless someone searches through the code looking for every API call, you will have to request permission for and enable all of these.
- Dependencies were never version-locked, so installations made recently will likely fail with breaking changes such as these.
- Python 3.8+ (IIRC?) is not supported (try running on 3.6 perhaps)
- There have been a host of changes to Discord's API and by extension discord.py.
